In [1]:
import numpy as np
import pandas as pd

In [2]:
## Series of 1-D array

In [3]:
s = pd.Series([10,20,30,40])

In [4]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
pop = pd.Series([1444 , 1393 , 323 , 278],
                index = ["India", "China", "USA", "Indonesia"],
                name = "population_millions"
                )

In [9]:
print(pop)

India        1444
China        1393
USA           323
Indonesia     278
Name: population_millions, dtype: int64

In [10]:
print(pop[pop>500])

India    1444
China    1393
Name: population_millions, dtype: int64

In [13]:
q1 = pd.Series({"laptops":120,"phone":340,"tablets":77})
q2 = pd.Series({"phones":44,"laptops":474,"watches":73})
print(q1+q2)

laptops    594.0
phone        NaN
phones       NaN
tablets      NaN
watches      NaN
dtype: float64

In [14]:
#Data Frames

In [16]:
df = pd.DataFrame({
    "name": ["Ashu", "Bill", "Chen", "Diya", "Evan"],
    "dept": ["IT", "HR", "IT","Finance","HR"],
    "salary": [52000,48000,47999,75000,50000],
    "city": ["Delhi", "Mumbai", "Surat","Agra","Delhi"]
})

In [17]:
print(df)

   name     dept  salary    city
0  Ashu       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   Surat
3  Diya  Finance   75000    Agra
4  Evan       HR   50000   Delhi

In [18]:
print(df.shape)

(5, 4)

In [19]:
print(list(df.columns))

['name', 'dept', 'salary', 'city']

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   dept    5 non-null      object
 2   salary  5 non-null      int64
 3   city    5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [21]:
df.describe()

             salary
count      5.000000
mean   54599.800000
std    11524.031421
min    47999.000000
25%    48000.000000
50%    50000.000000
75%    52000.000000
max    75000.000000

In [24]:
raw = pd.DataFrame({
    "order_id":["1001","1002","1003"],
    "amount":["2500","1800","1700"]
})

In [25]:
print(raw)

  order_id amount
0     1001   2500
1     1002   1800
2     1003   1700

In [26]:
print(raw["amount"].sum())

250018001700

In [27]:
clean = raw.copy()

In [28]:
clean["order_id"] = pd.to_numeric(clean["order_id"])
clean["amount"] = pd.to_numeric(clean["amount"])

In [29]:
print(clean.sum())

order_id    3006
amount      6000
dtype: int64

In [30]:
print(clean["amount"].sum())

6000

In [31]:
df

   name     dept  salary    city
0  Ashu       IT   52000   Delhi
1  Bill       HR   48000  Mumbai
2  Chen       IT   47999   Surat
3  Diya  Finance   75000    Agra
4  Evan       HR   50000   Delhi

In [32]:
people = df.set_index("name")

In [33]:
people

         dept  salary    city
name
Ashu       IT   52000   Delhi
Bill       HR   48000  Mumbai
Chen       IT   47999   Surat
Diya  Finance   75000    Agra
Evan       HR   50000   Delhi

In [35]:
print(people.loc["Ashu"])

dept         IT
salary    52000
city      Delhi
Name: Ashu, dtype: object

In [37]:
print(people.loc[["Ashu"],["salary"]])

      salary
name
Ashu   52000

In [38]:
print(people.iloc[0])

dept         IT
salary    52000
city      Delhi
Name: Ashu, dtype: object

In [39]:
print(people.iloc[0:30],[0,2])

         dept  salary    city
name
Ashu       IT   52000   Delhi
Bill       HR   48000  Mumbai
Chen       IT   47999   Surat
Diya  Finance   75000    Agra
Evan       HR   50000   Delhi [0, 2]

In [41]:
print(people[people["salary"]<4500])

Empty DataFrame
Columns: [dept, salary, city]
Index: []

In [43]:
print(people[(people["dept"] == "IT") & (people["salary"] < 49000)])

     dept  salary   city
name
Chen   IT   47999  Surat

In [46]:
print(people.query("dept == 'IT' "))

     dept  salary   city
name
Ashu   IT   52000  Delhi
Chen   IT   47999  Surat

In [47]:
# Missing Data

In [51]:
messy = pd.DataFrame({
    "produc":["pen","Book","Bag","Lamp","Mug"],
    "price":[20,np.nan,850,1200,np.nan],
    "rating":[4.1,4,np.nan,4.5,3.9]
})

In [52]:
messy

  produc   price  rating
0    pen    20.0     4.1
1   Book     NaN     4.0
2    Bag   850.0     NaN
3   Lamp  1200.0     4.5
4    Mug     NaN     3.9

In [53]:
messy.isna().sum()

produc    0
price     2
rating    1
dtype: int64

In [54]:
filled = messy.copy()

In [56]:
filled["price"] = filled["price"].fillna(filled["price"].mean())

In [57]:
filled["rating"] = filled["rating"].fillna(filled["rating"].median())

In [58]:
print(filled)

  produc   price  rating
0    pen    20.0    4.10
1   Book   690.0    4.00
2    Bag   850.0    4.05
3   Lamp  1200.0    4.50
4    Mug   690.0    3.90